### ISSUE TITLE
Issue with insertion, print, free function

### ISSUE THREAD

**Issue by charlieroth** [Deadlocked007/240TestPrep#1]
@Deadlocked007 Shouldn't the functions also take another argument of the `treeNode * node`? Otherwise there is no way to iterate over the tree. I know you could also write a find function but if you pass a `treeNode * node` then we can recursively insert nodes.

So I would give the functions this way:

```
treeNode* insert(treeNode * node, int value) {
  return NULL;
}

void freeTree(treeNode * node) {
}

char* printTree(treeNode * node) {
  return NULL;
}
```

Just something to consider. I know we don't know how we would be given this task on the exam but if you look around the internet for implementations of BSTs you will see that they pass a node as an argument to allow recursive insertion, printing and freeing.

Thanks for the practice problem!

**Comment by szaneer** [comment]
You're right I totally forgot to put it in! Thank you!
